using UnityEngine;

public class Rigidbody2D : MonoBehaviour
{
    private Vector3 velocity;
    private new Transform transform;

    private void Awake()
    {
        velocity.y = 5;
        transform = GetComponent<Transform>();
        var collider = GetComponent<CustomCollider2D>();
        collider.onCollisionEnter2D += (CustomCollision col) =>
        {
            velocity = -velocity + Random.insideUnitSphere;
            velocity.z = 0;
            velocity = velocity.normalized;
        };
    }

    private void FixedUpdate()
    {
        transform.position += velocity * 50.0f * Time.deltaTime;
    }
}
